config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :post, counter_cache: :comments_counter
  after_save :increment_counter

  def increment_counter
    post.update(comments_counter: (post.comments_counter || 0) + 1)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :post, counter_cache: :likes_counter
  after_save :increment_counter

  def increment_counter
    post.update(likes_counter: (post.likes_counter || 0) + 1)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', counter_cache: :posts_counter
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  after_save :increment_counter

  def increment_counter
    user.update(posts_counter: (user.posts_counter || 0) + 1)
  end

  def recent_comments(count: 5)
    comments.order(created_at: :desc)[0, count]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts(count: 3)
    Post.where(user_id: id).order(created_at: :desc)[0, count]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    comment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: } }
    end
  end

  def create
    @user = current_user
    puts params
    @post = Post.find(params[:post_id])
    comment = Comment.new(params.require(:comment).permit(:text))
    puts comment.user_id = @user.id
    puts comment.post_id = @post.id
    respond_to do |format|
      format.html do
        if comment.save
          comment.increment_counter
          flash[:success] = 'Comment created!'
          redirect_to user_post_path(@user, @post)
        else
          flash.now[:error] = 'Comment not created!'
          render :new, locals: { comment: }
        end
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    like = Like.new
    like.post_id = @post.id
    like.user_id = @user.id
    if like.save
      like.increment_counter
      flash[:success] = 'You liked this post'
    else
      flash[:error] = 'You already liked this post'
    end
    redirect_to user_post_path(@user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @all_posts = Post.where(user_id: params[:user_id]).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @user = current_user
    post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: } }
    end
  end

  def create
    @user = current_user
    post = Post.new(params.require(:post).permit(:text, :title))
    puts post.user_id = @user.id
    respond_to do |format|
      format.html do
        if post.save
          post.increment_counter
          flash[:success] = 'Post created!'
          redirect_to user_posts_path(@user)
        else
          flash.now[:error] = 'Post not created!'
          render :new, locals: { post: }
        end
      end
    end
  end

  def get_user_name(user_id)
    User.find(user_id).name
  end

  def get_all_comments(post_id)
    Comment.where(post_id:).order(created_at: :desc)
  end

  helper_method :get_user_name, :get_all_comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @all_posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<% stylesheet_link_tag 'users/index' %>
<div id="add-new-page" class="flex flex-col items-center gap-16 p-10">
  <h1>Create a New Comment</h1>
  <%= form_with model: comment, url: user_post_comments_path(@user, @post), method: :post, local: true do |form| %>
    <%= form.text_area :text, rows: 10, placeholder: 'What do you think about this post ...' %>
    <%= form.submit "Submit" %>
  <% end %>
</div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <% stylesheet_link_tag "users/index" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <% flash.each do |type, msg| %>
      <div id="box-border" class="p-4 flex justify-center mt-5 mr-1">
        <%= msg %>
      </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_comments_tile.html.erb
<% stylesheet_link_tag 'users/index' %>
<div id="box-border" class="p-4">
  <ul class="flex flex-col gap-1">
    <% comments.each do |comment| %>
      <li class="flex gap-3">
        <p class="font-semibold"><%= get_user_name(comment.user_id) %>:</p>
        <p class="text-sm"><%= comment.text %></p>
      </li>
    <% end %>
  </ul>
  <% if comments.length == 0 %>
    <p>No Comments yet</p>
  <% end %>
</div>

app/views/posts/_expanded_post_tile.html.erb
<% stylesheet_link_tag 'users/index' %>
<div id="box-border" class="p-4 flex flex-col gap-7">
  <div class="flex space-x-4 justify-between">
    <h2 class="text-xl">Post #<%= post.id %> by <%= @user.name %></h2>
    <div class="flex flex-row gap-5">
      <p>Comments <%= post.comments_counter || 0 %></p>
      <p>Likes <%= post.likes_counter || 0 %></p>
    </div>
  </div>
  <p><%= post.text %></p>
  <div class="flex self-end gap-1">
  <%= link_to new_user_post_comment_path @user, @post do %>
    <button class="h-10 w-32 cursor-pointer">Comment</button>
  <% end %>
  <%= form_with model: Like.new, url: user_post_likes_path(@user, @post), method: :post do %>
    <button class="h-10 w-32 cursor-pointer">Like</button>
  <% end %>
  </div>
</div>

app/views/posts/_post_tile.html.erb
<% stylesheet_link_tag 'users/index' %>

<%= link_to user_post_path(user, post) do %>
<div id="box-border" class="p-4 flex flex-col">
  <h2 class="text-lg mb-4">Post #<%= post.id %></h2>
  <p class="overflow-hidden whitespace-nowrap text-ellipsis"><%= post.text %></p>
  <div class="lex gap-5 self-end">
    <p>Comments <%= post.comments_counter || 0 %></p>
    <p>Likes <%= post.likes_counter || 0 %></p>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<% stylesheet_link_tag 'users/index' %>
<div class="p-10 flex flex-col gap-7">
  <%= render 'users/user_tile', user: @user %>
  <div class="mt-0 mr-auto ">
    <%= link_to new_user_post_path(@user) do %>
      <button id="box-border" class="p-4 cursor-pointer h-12">Create a new Post</button>
    <% end %>
  </div>
  <ul class="list-none flex flex-col gap-7">
    <% @all_posts.each do |post| %>
      <li>
        <%= render 'posts/post_tile', post: post, user: @user, expanded: false %>
        <%= render 'posts/comments_tile', comments: post.recent_comments %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<% stylesheet_link_tag 'users/index' %>
<div id="add-new-page" class="flex flex-col items-center gap-16 p-10">
  <h1 class="pb-1">Create a New Post</h1>
  <%= form_with model: post, url: user_posts_path(@user), method: :post, local: true do |form| %>
    <%= form.text_field :title, placeholder: 'Enter Title' %>
    <%= form.text_area :text, rows: 10, placeholder: "Enter post " %>
    <%= form.submit "Submit" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="flex flex-col p-10">
  <%= render 'posts/expanded_post_tile', post: @post %>
  <%= render 'posts/comments_tile', comments: get_all_comments(@post.id) %>
</div>

app/views/users/_user_tile.html.erb
<% stylesheet_link_tag 'users/index' %>

<%= link_to user do %>
<div class="flex m-5 h-32 gap-5">
    <div class="w-32 h-full object-cover">
        <img src="<%= user.photo %>" alt="Profile Picture">
    </div>
    <div id="box-border" class="m-3 p-5 flex flex-col justify-center">
        <h1 class="font-black self-end"><%= user.name %></h1>
        <p class="text-lg self-end">Number of Posts: <%= user.posts_counter || 0 %></p>
    </div>
</div>
<% end %>

app/views/users/index.html.erb
<div class="p-10">
  <ul class="list-none flex flex-col gap-5">
    <% @users.each do |user| %>
      <li>
        <%= render 'users/user_tile', user: user %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<% stylesheet_link_tag 'users/index' %>
<div class="p-10 flex flex-col gap-7">
  <%= render 'users/user_tile', user: @user %>
  <div id="box-border" class="p-4 flex flex-col gap-4 border-solid">
    <p class="text-base font-bold">Bio</p>
    <p><%= @user.bio %></p>
    <%= link_to new_user_post_path(@user) do %>
      <button>Create a new Post</button>
    <% end %>
  </div>
   <ul>
    <% @all_posts.each do |post| %>
      <li>
          <%= render 'posts/post_tile', post: post, user:@user, expanded: false %>
      </li>
    <% end %>
  </ul>
  <div class="flex justify-center">
    <%= link_to user_posts_path(@user) do %>
      <button id="box-border" class="h-10 w-32 cursor-pointer">See all posts</button>
    <% end %>
  </div>
</div>